openapi: 3.0.0
info:
  title: ActTrader API - OpenAPI 3.0
  description: |-
    This is a ActTrader API based on the OpenAPI 3.0 specification.  
  version: '1.0'
servers:
  # Added by API Auto Mocking Plugin
  - description: sandbox endpoint
    url: http://stest-01.sysfx.com:10013/
tags:
  - name: accounts
    description: Everything about account ActTrader API
paths:
  /accounts:
    get:
      tags:
        - accounts
      summary: method to get accounts
      description: Get accounts list
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountList'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponce'
          description: An unexpected error response.
      security:
        - Bearer: []
  /shifts:
    get:
      tags:
        - accounts
      summary: method to get shifts
      description: Get trader shifts
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shifts'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponce'
          description: An unexpected error response.
      security:
        - Bearer: []
components:
  schemas:
    Account:
      type: object
      
      example: 
        accountId: 10
        balance: '10001.01'
        currency: USD
        
      properties:
        accountId:
          type: integer
        balance:
          type: string
        currency:
          type: string
          
    AccountList:
      type: object
      properties:
        data:
          items: 
            $ref: '#/components/schemas/Account'
          type: array
        success: 
          type: boolean
      example:
        success: true
        data:
          - id: 100
            balance: '10000.01'
            currency: USD
          - id: 101
            balance: '10000.01'
            currency: EUR

    Shift:
      type: object
      
      example: 
        instrument_id: 10
        bid: '0.01'
        ask: '0.01'
        distance: '0.01'
        
      properties:
        instrument_id:
          type: integer
        bid:
          type: string
        ask:
          type: string
        distance:
          type: string

    Shifts:
      type: object
      properties:
        data:
          items: 
            $ref: '#/components/schemas/Shift'
          type: array
        success: 
          type: boolean
      example:
        success: true
        data:
          - instrument_id: 1
            bid: '0.01'
            ask: '0.01'
            distance: '0.01'
          - instrument_id: 3
            bid: '0.01'
            ask: '0.01'
            distance: '0.01'

    errorResponce:
      example:
        success: false
        error: LOAD_FAILED
      properties:
        success:
          type: boolean
        error:
           type: string
      type: object
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer