openapi: 3.0.0
info:
  title: Alerts API - OpenAPI 3.0
  description: |-
    This is a Strategy Server based on the OpenAPI 3.0 specification.  
  version: '1.0'
servers:
  # Added by API Auto Mocking Plugin
  - description: sandbox endpoint
    url: https://alerts.acttrader.com/api/
tags:
  - name: ActTrader alerts
    description: Everything about your ActTrader alerts
paths:
  /alerts:
    get:
      tags:
        - ActTrader alerts
      summary: Get all alerts
      operationId: getStrategyList
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertsList'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
          description: An unexpected error response.
      security:
        - Bearer: []
  /alert:
    post:
      tags:
        - ActTrader alerts
      summary: Add a new alert
      operationId: addAlert
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alert'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertId'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
          description: An unexpected error response.
      security:
       - Bearer: []
  /alert/{id}:
    get:
      tags:
        - ActTrader alerts
      summary: Get particular alert by ID
      operationId: geAlert
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
          description: An unexpected error response.
      security:
        - Bearer: []
    put:
      tags:
        - ActTrader alerts
      summary: Update alert by ID
      operationId: updateAlert
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alert'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
          description: An unexpected error response.
      security:
        - Bearer: []
    delete:
      tags:
        - ActTrader alerts
      summary: Delete alert by ID
      operationId: deleteAlert
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Successful operation
          
      security:
        - Bearer: []
components:
  schemas:
    Alert:
      type: object
      properties:
        instrument:
          type: string
          example: EURUSD
        price:
          type: number
          example: 1.1234
        side:
          type: number
          example: 1
        commentary:
          type: string
          example: alert commentary
        sellbuy:
          type: string
          example: SELL
    AlertId:
      type: object
      properties:
        id:
          type: integer
          example: 10
        instrument:
          type: string
          example: EURUSD
        price:
          type: number
          example: 1.1234
        side:
          type: number
          example: 1
        commentary:
          type: string
          example: alert commentary
        sellbuy:
          type: string
          example: SELL
    AlertsList:
      type: object
      properties:
        alerts:
          items: 
            $ref: '#/components/schemas/AlertId'
          type: array
      example:
        alerts:
          - id: 100
            instrument: EURUSD
            price: 1.2345
            side: 1
            commentary: alert commentary
            sb: BUY
          - id: 101
            instrument: GBPUSD
            price: 1.5678
            side: -1
            commentary:
            sellbuy: SELL
    response:
      example:
        code: 40001
        message: INVALID_ARGUMENT
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      type: object
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer